osrf/vrx

docker/Dockerfile, wamv_gazebo/launch/localization_example.launch
As seen in  3e44023d306776374 (or the old bitbucket [url](https://bitbucket.org/osrf/vrx/pull-requests/216/fix-issue-188/diff)), the GPS and IMU links were changed from "fixed joint" to "revolute joint" in the WAMV URDF. This leaves the robot localization example from wamv_gazebo (run via `roslaunch vrx_gazebo vrx.launch` and then `roslaunch wamv_gazebo localization_example.launch`) broken.
A simple fix is to add a joint state publisher to publish the transforms of the "revolute joints". `joint-state-publisher` can be installed via `sudo apt install ros-melodic-joint-state-publisher`.
You can verify this works by monitoring the
`rostopic hz /wamv/robot_localization/odometry/filtered` 
before and after the fix. Before the fix, robot localization node will give warnings complaining of …
=> Fix  #199 missing static transforms in localization example

vrx_gazebo/docs/pm_sampling.py, vrx_gazebo/msgs/CMakeLists.txt, vrx_gazebo/scripts/generate_avoid_obstacles_buoys, vrx_gazebo/src/vrx_gazebo_python/generator_scripts/world_generator/generate_worlds.py, wave_gazebo_plugins/CMakeLists.txt, wave_gazebo_plugins/include/wave_gazebo_plugins/Utilities.hh, wave_gazebo_plugins/include/wave_gazebo_plugins/Wavefield.hh
Three minor changes to get the basic test case: 
```bash
$ roslaunch vrx_gazebo sandisland.launch
```
running on macOS Catalina 10.15.4 with Python3, ROS Melodic, Gazebo 11 (I appreciate this is not a supported configuration).
***Issue 1:*** The protobuf issue causes these runtime errors on macOS:
1. An error caused by importing `header.proto` and `time.proto` into the sources list:
```console
[libprotobuf ERROR google/protobuf/descriptor_database.cc:120] File already exists in database: time.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1356] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): …
```
=> Changes to support Gazebo11 and Python3 on macOS 10.15.4

wamv_gazebo/urdf/dynamics/wamv_gazebo_dynamics_plugin.xacro, wave_gazebo/world_models/ocean_waves/model.xacro, wave_gazebo/world_models/ocean_waves/model.xacro.erb
Added parameters for size and scale of waves.
Needed for https://github.com/osrf/vorc/pull/1
A larger wave plane is needed for VORC as the terrain covers a larger area.
I guessed this is how to get a bigger wave geometry? It gives me more blue stuff alright. If this isn't the proper way, please let me know how to do it right.
=> Add parameters for customizing wave size

vrx_gazebo/CMakeLists.txt, vrx_gazebo/launch/usv_joydrive.launch, vrx_gazebo/launch/usv_keydrive.launch, wamv_gazebo/urdf/thruster_layouts/wamv_gazebo_thruster_config.xacro
Added a few thruster parameters for VORC.
Added an install command for `twist2thrust.py`, otherwise I got
```
ERROR: cannot launch node of type [vrx_gazebo/twist2thrust.py]: Cannot locate node of type [twist2thrust.py] in package [vrx_gazebo]. Make sure file exists in package path and permission is set to executable (chmod +x)
```
=> Thruster parameters for VORC

wamv_gazebo/urdf/sensors/wamv_pinger.xacro
Parameterize `frameId` in wamv_pinger xacro macro.
=> Add parameter to wamv_pinger macro

.gitignore, Changelog.md, usv_gazebo_plugins/include/usv_gazebo_plugins/usv_gazebo_dynamics_plugin.hh, usv_gazebo_plugins/src/usv_gazebo_dynamics_plugin.cc
Exposes additional hydrodynamic parameters, specifically added mass and quadratic drag parameters.  These are used by the USV model in the Frontiers paper.  Also used for a non-VRX USV model.
To test, simply run the standard example...
```
roslaunch vrx_gazebo vrx.launch
```
Nothing should change since the current WAM-V model doesn't specify these parameters so the default, nominal values are used by they hydro model.
=> New hydro params

vrx_gazebo/src/stationkeeping_scoring_plugin.cc, vrx_gazebo/src/wayfinding_scoring_plugin.cc
Allow custom topics to be used for station-keeping and wayfinding tasks, to support VORC.
Test by editing existing world files for the tasks, e.g. add custom tags under the plugin in  `worlds/stationkeeping_task.world.xacro`:
```
<plugin name="stationkeeping_scoring_plugin"
filename="libstationkeeping_scoring_plugin.so">
<goal_topic>/aaaaaaaaaaaaaaaaaaaaaaa</goal_topic>
<rms_error_topic>/bbbbbbbbbbbbbbbbbbb</rms_error_topic>
<pose_error_topic>/ccccccccccccccccccc</pose_error_topic>
```
```
$ roslaunch vrx_gazebo station_keeping.launch
$ rostopic list
/aaaaaaaaaaaaaaaaaaaaaaa
/bbbbbbbbbbbbbbbbbbb
/ccccccccccccccccccc
/clock
/gazebo/link_states
…
```
Similarly for wayfinding task in `worlds/wayfinding_task.world.xacro`:
```
<plugin name="wayfinding_scoring_plugin" …
```
=> Parse custom topics for station-keeping and wayfinding tasks

wamv_gazebo/urdf/sensors/wamv_gps.xacro
Modified `wamv_gps.xacro` to accept latitude, longitude, and elevation parameters, with default coordinates set to VRX sandisland.world coordinates. Related to issue osrf/vorc#24
Added parameters for lat/lon/elev
```
<xacro:macro name="wamv_gps" params="name:=gps x:=0.3 y:=0 z:=1.3 R:=0 P:=0 Y:=0 lat:=21.30996 lon:=-157.8901 elev:=0.0">
```
Parameters used for map origin
```
<referenceLatitude>${lat}</referenceLatitude>
<referenceLongitude>${lon}</referenceLongitude>
<referenceAltitude>${elev}</referenceAltitude>
```
=> Added lat/lon/elev parameters to wamv_gps.xacro input parms

.github/workflows/docker_release.yml, docker/Dockerfile, docker/build.bash
This pull request should fix issue #69 . The idea is that when a new release tag is created, we build a Docker image and push it to DockerHub automatically. A release tag is something that starts with `v` followed by the version number (e.g.: `v1.3.1`).
This GitHub workflow™ builds the Nvidia and non-Nvidia versions of the Docker image that uses Ubuntu Bionic/ROS Melodic/Gazebo9.
I did some testing and the images were correctly uploaded to https://hub.docker.com/r/osrf/vrx/tags
=> Automatic release of Docker images

usv_gazebo_plugins/CMakeLists.txt, vrx_gazebo/CMakeLists.txt, vrx_gazebo/msgs/CMakeLists.txt, wamv_gazebo/CMakeLists.txt, wave_gazebo_plugins/CMakeLists.txt
To support adding CI for VORC https://github.com/osrf/vorc/pull/21
CMake policies [CMP0046](https://cmake.org/cmake/help/v3.0/policy/CMP0046.html), [CMP0054](https://cmake.org/cmake/help/v3.1/policy/CMP0054.html), and [CMP0071](https://cmake.org/cmake/help/git-stage/policy/CMP0071.html) started introducing warnings in CMake 3.10.2, 3.1.3, and 3.10, respectively.
These produce warnings when using newer CMake versions.
To reproduce the warnings, on Ubuntu 18.04 (target platform for ROS Melodic, `apt` ships CMake 3.10.2), compile from scratch:
```
$ rm -rf build devel log install
$ catkin_make
```
This PR removes those warnings properly.
`OLD` and `NEW` flags are set explicitly to appease CMake warnings.
Specifically, CMP0054 is for using variables in quotes in `FindBoost.cmake`, which we …
=> Set CMake 3.1+ policies explicitly to remove warnings

vrx_gazebo/include/vrx_gazebo/scoring_plugin.hh, vrx_gazebo/src/scoring_plugin.cc, vrx_gazebo/worlds/xacros/perception.xacro, vrx_gazebo/worlds/xacros/stationkeeping.xacro, vrx_gazebo/worlds/xacros/wayfinding.xacro
Adds optional SDF plugin parameter `<per_plugin_exit_on_completion>` to base class scoring plugin.
Defaults to true, which is original behavior.
If environment variable `VRX_EXIT_ON_COMPLETION` is specified, overwrites this parameter, as original behavior.
This allows each plugin to specify optionally to NOT shut down after the status changes to `"finished"`, which allows the combined use of plugins, one task after another, in the same run.
Example usage: VORC gymkhana task, where navigation task is followed by stationkeeping, and we don't want to shut down Gazebo when the navigation task has been completed.
=> Add per-plugin exit flag to scoring plugin

vrx_gazebo/launch/generate_worlds.launch, vrx_gazebo/src/vrx_gazebo/generate_worlds.py
Probably not the most elegant solution, but as generic and quick as I could do.
I put the YAML generation where it is, because everything from `create_xacro_file()` downstream is creating a xacro file from a dictionary, pretty generic code, so the YAML stuff needed to go above that level.
Unfortunately, this means we need to duplicate the specification of the pinger position in the vrx-docker task_config YAML file, given the way the gymkhana scoring plugin is currently implemented.
The alternative is to specify the pinger position only once in the YAML file, but then here we would need to check for `pinger_[x | y | z]` inside `create_xacro_file()` and generated the YAML file from there. That would make the code too coupled and cluttered with specific checks.
=> Generate acoustic pinger YAML file for Gymkhana evaluation

vrx_gazebo/CMakeLists.txt
Working with Noetic on Cloudsim.  The buoy generator program uses Python 2.  For now, commented this out of the the CMakelists.txt file and added https://github.com/osrf/vrx/issues/242 to remind us to do this later.
=> Removing buoy generator b/c need to port to Python 3

vrx_gazebo/config/diffdrive.yaml
Addresses this issue: https://github.com/osrf/vrx/issues/262
Updated config file for joy teleop node, added more instructions to the wiki https://github.com/osrf/vrx/wiki/driving_teleop_tutorial and verified that both keyboard and gamepad teleop support thruster articulation examples.
=> Teleop thruster articulation

vrx_gazebo/launch/station_keeping.launch, vrx_gazebo/worlds/stationkeeping_task.world.xacro, vrx_gazebo/worlds/sydneyregatta.xacro, wamv_gazebo/urdf/sensors/wamv_gps.xacro
- Set in sydneyregatta world
- GPS headings updated
- Goal position updated
To run:
`roslaunch vrx_gazebo station_keeping.launch`
To move WAM-V via keyboard:
`roslaunch vrx_gazebo usv_keydrive.launch`
To monitor score:
`rostopic echo /vrx/station_keeping/pose_error`
Navigate to the goal pose and hold station. The best solutions will minimize the difference between the goal pose and the actual pose of the vehicle over the duration of the task.
Start the example: roslaunch vrx_gazebo station_keeping.launch
Subscribe to the task-specific topics provided by the stationkeeping scoring plugin:
The station-keeping goal (given as a geographic_msgs/GeoPoseStamped message):
rostopic echo /vrx/station_keeping/goal
The current position error values:
rostopic echo /vrx/station_keeping/pose_error …
=> Update Station Keeping Task

vrx_gazebo/CMakeLists.txt, vrx_gazebo/include/vrx_gazebo/navigation_scoring_plugin.hh, vrx_gazebo/include/vrx_gazebo/wildlife_scoring_plugin.hh, vrx_gazebo/launch/wildlife.launch, vrx_gazebo/models/animal_buoys/model.config, vrx_gazebo/models/animal_buoys/model.sdf, vrx_gazebo/models/crocodile_buoy/model.sdf, vrx_gazebo/models/platypus_buoy/model.sdf, vrx_gazebo/models/turtle_buoy/model.sdf, vrx_gazebo/src/wildlife_scoring_plugin.cc, vrx_gazebo/worlds/sydneyregatta.xacro, vrx_gazebo/worlds/wildlife_task.world.xacro
See issue #276.
This scoring plugin isn't trivial, so I decided to split it in two pull request. This is the first one:
* It adds a new world (`wildlife_task.world.xacro`).
* It adds a new launch file for launching the previous world (`wildlife.launch`).
* It adds a new model (`animal_buoys`) that combine all the animal buoys into a single model. The reason for this is that it will be easier in the future to create different combinations for each run. Every configuration will be captured into a separate model containing also the `FollowPlugin` parameters. For now, I didn't move the plugins to this new model.
* It adds a new scoring plugin (`wildlife_scoring_plugin`).
The functionality added so far is:
* The plugin parses all the SDF parameters. 
* The plugin publishes all the animal poses …
=> Wildlife scoring plugin - part 1

vrx_gazebo/include/vrx_gazebo/waypoint_markers.hh, vrx_gazebo/models/crocodile_buoy/model.sdf, vrx_gazebo/models/platypus_buoy/model.sdf, vrx_gazebo/models/turtle_buoy/model.sdf, vrx_gazebo/src/follow_plugin.cc, vrx_gazebo/src/waypoint_markers.cc
We had a minor issue with the way markers were designed. We always had to pass an ID to the `DrawMarker()` function. This was causing a problem when multiple plugins were using this function without knowing each other. All of the plugins started using the same IDs (starting with `0`), and then, sharing the same IDs creating an undesired effect.
This pull request allows to call `DrawMarker()` without explicitly passing an Id. If that's the case, the plugin will use an internal `id` member variable than can be optionally initialized with an `<initial_id>` SDF parameter. 
A second alternative would be to add this `<initial_id>` to each plugin using markers (passing different values to each of the plugins) and not having to modify the `WaypointMarkers` class. However that requires more code …
=> Create new markers without passing Id

vrx_gazebo/src/ball_shooter_plugin.cc, vrx_gazebo/worlds/gymkhana.world.xacro, vrx_gazebo/worlds/perception_task.world.xacro, vrx_gazebo/worlds/scan_dock_deliver.world.xacro, vrx_gazebo/worlds/stationkeeping_task.world.xacro, vrx_gazebo/worlds/sydneyregatta.world.xacro, vrx_gazebo/worlds/wayfinding_task.world.xacro, vrx_gazebo/worlds/wildlife_task.world.xacro
This pull requests adjusts the `scale` parameter of the ocean waves to cover the entire Sydney Regatta world. I also fixed some incorrect link name that is needed for the wind plugin.
See the water behavior before this pull request:
And this is the water behavior after this pull request:
How to test it:
Go to the [VRX 2022 competition wiki page](https://github.com/osrf/vrx/wiki/vrx_2022-task_tutorials), scroll down to the very bottom and open all individual tutorials for each task. You should see in all the worlds the water covering the entire arena.
=> Fix water scaling and wind

vrx_gazebo/launch/demo_thrusterconfigs.launch
As part of documenting the propulsion configuration, I created a launch file to spawn the three variants in the same Sydney world.  This PR just adds the launch file, so should not affect anything else.  Just keeping the launch file for posterity.
Test by running 
```
roslaunch vrx_gazebo demo_thrusterconfigs.launch 
```
Added last section of wiki: https://github.com/osrf/vrx/wiki/tutorials-PropulsionConfiguration
=> Propulsion configuration demo launch file

vrx_gazebo/models/dock_2016/model.sdf.erb, vrx_gazebo/models/dock_2016_dynamic/model.sdf.erb, vrx_gazebo/models/dock_2018_dynamic/model.sdf.erb, vrx_gazebo/models/dock_2022/model.sdf.erb, vrx_gazebo/models/dock_2022_dynamic/model.sdf.erb, vrx_gazebo/models/placard_2022/model.sdf
This pull request replaces the collision element of the 2022 placard. Before we were using the mesh directly. We're now using a few boxes strategically placed. Usually simple shapes offer better performance than meshes while checking collisions.
=> Simple shapes as collision elements in the 2022 placards

vrx_gazebo/models/ball_shooter/meshes/ball_shooter.dae
See Issue #344 for explanation.
Original error message is...
```
[ERROR] [1631215004.480044470, 413.401000000]: Could not load resource [package://vrx_gazebo/models/ball_shooter/meshes/ball_shooter.dae]: Collada: package://vrx_gazebo/models/ball_shooter/meshes/ball_shooter.dae - Expected end of <author> element.
```
Appears that the process didn't like the single XML tags, so removed empty tags in this PR.  
Still missing texture images as described in Issue #344
=> Ball Shooter Model: Partial fix for XML format

vrx_gazebo/include/vrx_gazebo/gymkhana_scoring_plugin.hh, vrx_gazebo/include/vrx_gazebo/navigation_scoring_plugin.hh, vrx_gazebo/include/vrx_gazebo/scoring_plugin.hh, vrx_gazebo/msg/Task.msg, vrx_gazebo/src/gymkhana_scoring_plugin.cc, vrx_gazebo/src/navigation_scoring_plugin.cc, vrx_gazebo/src/scoring_plugin.cc
I moved the logic to account for the collisions to the base scoring plugin and include it in the task message.
=> Adding number of collisions to the task message

vrx_gazebo/launch/generate_worlds.launch
`generate_worlds.launch` is missing a .py extension which causes a crash. The extension was added to the file in PR #269, but this reference to it was overlooked.
To test, it is sufficient to observe that the files in [vrx_gazebo/scripts](https://github.com/osrf/vrx/tree/master/vrx_gazebo/scripts) were renamed in [this commit](https://github.com/osrf/vrx/commit/5589026cf82f9940d7d9ad73406a729edb4a07d1), but the reference in this launch file was not.
=> Fix missing filename extension in generate_worlds.launch

vrx_gazebo/launch/vrx.launch, vrx_gazebo/worlds/example_course.world.xacro
This resolves issue #279
To test, run:
```
roslaunch vrx_gazebo vrx.launch
```
You should see the light buoy, docks, gymkhana course and our 3 animals:
=> adding 2022 elements to vrx.launch

vrx_gazebo/launch/pinger.launch
While testing the [acoustic pinger tutorial](https://github.com/osrf/vrx/wiki/acoustic_pinger_tutorial), the following command failed:
```
roslaunch vrx_gazebo pinger.launch
```
with this error message:
```
ERROR: cannot launch node of type [vrx_gazebo/pinger_visualisation.py]: Cannot locate node of type [pinger_visualisation.py] in package [vrx_gazebo]. Make sure file exists in package path and permission is set to executable (chmod +x)
```
The problem is that `pinger.launch` contains a typo. This pull request fixes it.
=> Fix pinger.launch

vrx_gazebo/worlds/scan_dock_deliver.world.xacro, vrx_gazebo/worlds/xacros/include_all_xacros.xacro, vrx_gazebo/worlds/xacros/scan_dock_deliver.xacro
Adds scan_dock_deliver.xacro, for use with the `generate_worlds` script to create practice worlds. This PR should be tested in conjunction with [PR 40](https://github.com/osrf/vrx-docker/pull/40) in the `vrx-docker` repo, using the testing instructions listed there.
=> Add a xacro for generating scan, dock, deliver worlds

vrx_gazebo/worlds/xacros/gymkhana.xacro, vrx_gazebo/worlds/xacros/include_all_xacros.xacro, vrx_gazebo/worlds/xacros/scan_dock_deliver.xacro
Adds gymkhana.xacro, for use with the `generate_worlds` script to create practice worlds. This PR should be tested in conjunction with [PR 41](https://github.com/osrf/vrx-docker/pull/41) in the `vrx-docker` repo, using the testing instructions listed there.
=> Add a xacro for generating gymkhana worlds

wamv_gazebo/launch/localization_example.launch
Now that [this patch](https://github.com/cra-ros-pkg/robot_localization/pull/705#issuecomment-971376750) has been merged into the `robot_localization` package, we'll need to exercise this functionality.
Until there's a new ROS noetic release, we'll need to install `robot_localization` manually to observe this functionality working.
How to test it:
1. First, compile `robot_localization` from source with our patch:
```
cd <your_vrx_ws>/src
git clone https://github.com/cra-ros-pkg/robot_localization.git
cd ..
catkin_make
```
2. Launch vrx as usual:
```
roslaunch vrx_gazebo vrx.launch
```
3. Launch our localization example
```
roslaunch wamv_gazebo localization_example.launch
```
You shouldn't see any warnings.
=> Suppress tf warnings

vrx_gazebo/launch/station_keeping.launch, vrx_gazebo/worlds/stationkeeping_task.world.xacro
This PR makes some small tweaks to the launch and world files for the station-keeping task demo.  These were created as part of the kickoff demonstration to illustrate parameterized wind for testing.  Exposing the `paused` argument in the launch file is typical and expected.
=> Adding wind and paused to stationkeeping demonstrations

vrx_gazebo/launch/generate_wamv.launch
Fixed the problem when running the simulation generate_wamv.launch fails.
Closes #417
=> fixed generate_wamv.launch

vrx_gazebo/config/wamv_config/component_compliance/numeric.yaml
Edited numeric.yaml such that a ```wamv_pinger``` can be added to a component.yaml if the user chooses to use yaml component generation. Related issue: #423
=> added ability to add wamv_pinger to component.yaml

vrx_gazebo/config/wamv_config/component_compliance/numeric.yaml, vrx_gazebo/include/vrx_gazebo/scoring_plugin.hh, vrx_gazebo/src/perception_scoring_plugin.cc, vrx_gazebo/src/scoring_plugin.cc, vrx_gazebo/src/stationkeeping_scoring_plugin.cc, vrx_gazebo/src/wayfinding_scoring_plugin.cc, vrx_gazebo/src/wildlife_scoring_plugin.cc, wave_gazebo_plugins/include/wave_gazebo_plugins/Wavefield.hh
See issue #420 and pull request #421 where there's a detailed conversation.
As described in [this pull request](https://github.com/ignitionrobotics/ign-math/pull/235), the `*FromLocal*()` functions contain a bug that has been fixed in Ignition Math. This patch instantiates a new ignition::math::SphericalCoordinates member variable in the base scoring plugin to be used for any derived scoring plugins.
Note that even in the updated version we still can't use `*FromLocal*()` directly, as it contains the version with the issue to preserve old behavior. In order to use the corrected version we need to call `PositionTransform()` directly.
=> Fix spherical coordinates FromLocal calls

vrx_gazebo/worlds/2022_practice/gymkhana0.world, vrx_gazebo/worlds/2022_practice/gymkhana1.world, vrx_gazebo/worlds/2022_practice/gymkhana2.world, vrx_gazebo/worlds/2022_practice/perception0.world, vrx_gazebo/worlds/2022_practice/perception1.world, vrx_gazebo/worlds/2022_practice/perception2.world, vrx_gazebo/worlds/2022_practice/scan_dock_deliver0.world, vrx_gazebo/worlds/2022_practice/scan_dock_deliver1.world, vrx_gazebo/worlds/2022_practice/scan_dock_deliver2.world, vrx_gazebo/worlds/2022_practice/stationkeeping0.world, vrx_gazebo/worlds/2022_practice/stationkeeping1.world, vrx_gazebo/worlds/2022_practice/stationkeeping2.world, vrx_gazebo/worlds/2022_practice/wayfinding0.world, vrx_gazebo/worlds/2022_practice/wayfinding1.world, vrx_gazebo/worlds/2022_practice/wildlife0.world, vrx_gazebo/worlds/2022_practice/wildlife1.world, vrx_gazebo/worlds/2022_practice/wildlife2.world, vrx_gazebo/worlds/xacros/usv_wind_plugin.xacro
Partially addresses issue #431 by modifying all values for the var_wind_time parameter so they are within the envelop. (Note that all but one of them were set to 1, so they are now all set to 2. Apparently we aren't relying on this parameter very much.)
Since the change is very minor, I don't think it's necessary to test every example world. To review, please look at the code changes to double check that nothing was changed except to increase `var_wind_time_constants` from 1 to 2, and that this was done for all 18 example files in `vrx_gazebo/worlds/2022_practice` (one of these was already 2, so 17 are changed).
You might also run one of the worlds just to make sure:
```
WORLD=stationkeeping0.world
roslaunch vrx_gazebo vrx.launch verbose:=true \
paused:=false \
wamv_locked:=true \ …
```
=> updating all var_wind_time 1 to 2 to keep within the envelope

vrx_gazebo/include/vrx_gazebo/gymkhana_scoring_plugin.hh, vrx_gazebo/launch/gymkhana.launch, vrx_gazebo/launch/vrx.launch, vrx_gazebo/src/gymkhana_scoring_plugin.cc, vrx_gazebo/worlds/2022_practice/gymkhana0.world, vrx_gazebo/worlds/2022_practice/gymkhana1.world, vrx_gazebo/worlds/2022_practice/gymkhana2.world, vrx_gazebo/worlds/gymkhana.world.xacro, vrx_gazebo/worlds/xacros/gymkhana.xacro
See issue #437. 
How to test it?
* Launch any of the `2022_practice` gymkhana worlds **(change the path to the world accordingly)**:
```
roslaunch vrx_gazebo gymkhana.launch verbose:=true world:=/home/caguero/vrx2022_ws/src/vrx/vrx_gazebo/worlds/2022_practice/gymkhana0.world
```
* Echo the set_pinger_position topic. Open a new terminal and run:
```
rostopic echo /wamv/sensors/pingers/pinger/set_pinger_position
```
You should observe that the pinger location is set to something different than the content of the `pinger.yaml` (-483, 295.5, 0).
* You can also teleoperate the robot to that location and echo the acoustic pinger:
```
/wamv/sensors/pingers/pinger/range_bearing
```
Verify that the range is close to `0`.
=> Fix pinger location in gymkhana task 

vrx_gazebo/config/wamv_config/component_compliance/numeric.yaml, vrx_gazebo/config/wamv_config/example_component_config.yaml
**1. Functional aspect:** It does not include the `wamv_pinger` component! If a custom WAM-V URDF is generated without this component, it still passes the compliance checks, but the sensor is not instantiated. When the Gymkhana task is launched, no data is published to `/wamv/sensors/pingers/pinger/range_bearing` topic. Consequently, it is impossible to localize the black box, and hence complete the task.
**2. Readability:** The example config sets a standard in front of developers, and hence it is common to assume that it is self-contained to its fullest abilities. However, the current version does not include all the allowable parameters for most of the components.
**1. Functional aspect:** `wamv_gps` and `wamv_imu` do nat have the parameter `post_Y`.
**2. Readability:** Sequence of the …
=> Update example_component_config.yaml and numeric.yaml for generating compliant WAM-V URDFs

vrx_gazebo/src/light_buoy_plugin.cc, vrx_gazebo/src/placard_plugin.cc
The solution that solved issue #451 for me was to make the gazebo subscriber within placard_plugin.cc allow latching. This way once even if the msgs are published before the subscriber is instantiated, the subscriber can still just get the last published message.
@M1chaelM, I apologize that I cannot think of a way to for you to replicate the issue without running my code, however, I think it makes sense as well to make this subscriber enable latching since the placard symbols are only ever published once. Please let me know if you are interested in seeing the behavior I am describing in #451 more in depth. You should also see that this change does not break anything, at least to my knowledge.
Update: I recently encountered the same issue for the STC buoy. It seemed that the subscriber was …
=> Made placard symbol subscriber enable latching

vrx_gazebo/include/vrx_gazebo/scoring_plugin.hh, vrx_gazebo/src/gymkhana_scoring_plugin.cc, vrx_gazebo/src/navigation_scoring_plugin.cc
I introduced an issue in #449 changing the default value of `timeoutScore` from `-1` to `200`. See how we're using `timeoutScore` in [scoring_plugin.cc::OnFinished()](https://github.com/osrf/vrx/blob/master/vrx_gazebo/src/scoring_plugin.cc#L278-L281). 
The original intent of that block of code is to update the current score to the `timeoutScore` only when `timeoutScore` is set. We were assuming that if `timeoutScore` isn't set, its value will be negative. Our change in #449 breaks this convention causing the score to always be updated to `timeoutScore` when a task timeouts. This is problematic in tasks such as stationkeeping or wayfinding because the task will always timeout.
How to test it?
1. Launch a stationkeeping task (**update the world path**) and verify that after the timeout, the …
=> Fix timeout score issue

.github/workflows/ci.yml
This PR addresses issue #468 by explicitly using version 2.4.0 of the checkout action. To test, simply observe that the CI for the noetic-gazebo11 test image does not fail.
=> pinning checkout action to v2.4.0

.github/workflows/ci.yml
Very basic Galactic/fortress CI.
Looking around the internet, it seems that there are a few efforts underway to provide github actions to build and test gazebosim/ros2 projects. 
* For example, the Gazebosim repository uses this workflow: https://github.com/gazebosim/gz-sim/blob/ign-gazebo6/.github/workflows/ci.yml
* However, it doesn't seem to be functional right now, and the vast majority of PRs are being merged with failed checks.
* So, for now I think we should take a simple approach and just see whether the build succeeds with `colcon`.
* Later we can also add static checking.
* When the fancier build and test tools are working better we can switch over.
To test:
* Review the output details and verify that they say what we expect them to say.
=> Add CI for gazebosim

vrx_gz/src/vrx_gz/bridges.py, vrx_gz/src/vrx_gz/launch.py, vrx_gz/src/vrx_gz/model.py, vrx_ros/launch/competition_local.launch.py
Signed-off-by: Ian Chen <ichen@openrobotics.org>
Follow up to #519, this PR fixes the ROS2 topics for the wamv. The problem was that the [ros_ign_bridge](https://github.com/gazebosim/ros_gz/tree/humble/ros_gz_bridge) is still using the `ignition.msgs.*` msg types instead of `gz.msgs` (see msg type table `README.md`) , presumably to keep compability with Fortress. 
All ROS2 topics should be working except the thruster cmd topic. It requires this https://github.com/gazebosim/gz-sim/pull/1681 to be forward ported from Fortress to Garden
The thrusters joint pos topic should work. 
```
ros2 topic pub': ros2 topic pub --once wamv/thrusters/right/pos std_msgs/msg/Float64 'data: -1
```
I removed more topic bridges that are not needed / used:
* `/wamv/imu/data` - commented out as there is no imu …
=> [Garden] Fix bridging Gz to ROS2 topics

vrx_gz/src/PolyhedraBuoyancyDrag.cc
Signed-off-by: Ian Chen <ichen@openrobotics.org>
Gazebo currently crashes if you pause then resume simulation. This is due to the `PolyhedraBuoyancyDrag` setting invalid link forces when `dt` is zero. The changes here just tell the plugin to skip computation when simulation is paused
To reproduce the crash:
1. Launch sim with any world (all of them should have buoys with the `PolyhedraBuoyancyDrag` plugin). 
1. Pause simulation
1. Play simulation -> crash
=> [Garden] Fix crash on when resuming simulation from paused state

vrx_gz/CMakeLists.txt, vrx_gz/src/BallShooterPlugin.cc, vrx_gz/src/BallShooterPlugin.hh, vrx_gz/src/vrx_gz/payload_bridges.py, vrx_gz/worlds/perception_task.sdf, vrx_gz/worlds/stationkeeping_task.sdf, vrx_gz/worlds/sydney_regatta.sdf, vrx_gz/worlds/wayfinding_task.sdf, vrx_gz/worlds/wildlife_task.sdf, vrx_urdf/vrx_gazebo/models/blue_projectile/model.config, vrx_urdf/vrx_gazebo/models/blue_projectile/model.sdf, vrx_urdf/wamv_gazebo/urdf/components/ball_shooter.xacro
Signed-off-by: Ian Chen <ichen@openrobotics.org>
Add ball shooter plugin and `blue_projectile` model to all worlds
To test:
1. Follow the instructions in #526 to generate and launch the world with the wamv urdf file. 
1. Run the cmd below to fire the ball shooter:
```
ros2 topic pub --once /wamv/shooters/ball_shooter/fire std_msgs/Empty
```
=> [Garden] Port Ball Shooter plugin

vrx_gz/CMakeLists.txt, vrx_gz/src/ScoringPlugin.cc, vrx_gz/src/ScoringPlugin.hh, vrx_gz/src/StationkeepingScoringPlugin.cc, vrx_gz/src/WildlifeScoringPlugin.cc, vrx_gz/src/WildlifeScoringPlugin.hh, vrx_gz/worlds/wildlife_task.sdf
This pull request ports the WildlifeScoringPlugin from Gazebo classic.
* Launch the wildlife_task world:
```
ros2 launch vrx_gz competition.launch.py world:=wildlife_task
```
* On a new terminal launch the joystick teleop node:
```
ros2 launch vrx_gz usv_joy_teleop.py
```
* On a new terminal check the `/vrx/task/info` topic:
```
ros2 topic  echo /vrx/task/info
```
Try circumnavigating the buoys (platypus clockwise and turtle counter clockwise). You should see messages of this type:
```
[Dbg] [WildlifeScoringPlugin.cc:409] platypus::link Virtual gate crossed clockwise! (25% completed)
```
**Bonus**: I enabled contact checking again. For some reason the topic subscription was removed.
=> [Garden] Wildlife scoring plugin - Part2

vrx_gz/src/GymkhanaScoringPlugin.cc, vrx_gz/src/GymkhanaScoringPlugin.hh, vrx_gz/src/NavigationScoringPlugin.cc, vrx_gz/src/NavigationScoringPlugin.hh, vrx_gz/src/PerceptionScoringPlugin.cc, vrx_gz/src/ScanDockScoringPlugin.cc, vrx_gz/src/ScoringPlugin.cc, vrx_gz/src/StationkeepingScoringPlugin.cc, vrx_gz/src/StationkeepingScoringPlugin.hh, vrx_gz/src/WayfindingScoringPlugin.cc, vrx_gz/src/WayfindingScoringPlugin.hh
Addresses issue #552 by:
* Removing all implementations of state transition functions (OnReady, OnRunning, OnFinished) from Stationkeeping, Wayfinding and Navigation tasks.
* Removing OnRunning from the Gymkhana task.
* Removing the unneeded OnCollision function from Stationkeeping.
* Flushing state transition messages and collision messages displayed by ScoringPlugin class.
* Replacing the call to Exit in the Perception class with ScoringPlugin::Finish().
Bonus:
* Changes the format of the OnFinished message to clarify that it is printing the time.
To test:
* Set the timeout value to a low number for all worlds:
```
cd vrx/vrx_gz/worlds
sed -i 's/duration>300/duration>60/g' *.sdf
```
* Run the Stationkeeping, Wayfinding, Perception, Navigation, Wildlife, Gymkhana and ScanDockDeliver …
=> Make state change and collision messages timely and uniform

vrx_gz/worlds/sydney_regatta.sdf
Related with #545 . Without this patch, the WAM-V is locked and can't be moved. 
How to test it?
* Launch the `sydney_regatta` world:
```
```
* Apply thrust:
```
ros2 topic pub /wamv/thrusters/right/thrust std_msgs/msg/Float64 data:\ 100.0\
```
You should see the WAM-V moving since you sent this command.
=> Do not lock the WAM-V in Sydney Regatta

vrx_gz/worlds/gymkhana_task.sdf, vrx_gz/worlds/navigation_task.sdf
A very minor tweak to make the starting position of the navigation course a little farther away from the starting position of the WAMV in the navigation and gymkhana tasks. The purpose of this is to make it a little harder to accidentally cross the first gate before the simulation has entered the `OnRunning` state (see discussion at #545).
To test:
* Start the navigation task
```
ros2 launch vrx_gz competition.launch.py world:=navigation_task
```
* Start teleop in a separate terminal.
```
ros2 launch vrx_gz usv_joy_teleop.py
```
* Try to drive the WAMV through the course as soon as possible.
* Confirm that the task enters the OnRunning state before you reach the first gate.
* Repeat for the gymkhana task.
=> Move navigation course farther from WAMV

vrx_urdf/vrx_gazebo/src/vrx_gazebo/compliance.py
This pull request fixes a Python issue when customizing a WAM-V. When the yaml configuration isn't compliant, instead of showing the expected error, we were showing the following error:
```
[generate_wamv.py-1] NameError: name 'yaml' is not defined
```
This patch fixes the problem.
Follow [this tutorial](https://github.com/osrf/vrx/wiki/2023-Customizing-the-WAM-V) and you shouldn't get any unexpected error.
=> [Garden] Fixing missing import

vrx_gz/models/coast_waves/model.sdf, vrx_gz/scripts/update_sea_state_params.sh, vrx_urdf/wamv_description/urdf/wamv_base.urdf.xacro
This pull request simplifies the process of updating the environmental conditions. Right now, all the wave parameters need to match among all the plugins that accept a `<wavefield>` parameter to show a consistent behavior.
Additionally, this patch enables the wind for the WAM-V, as it wasn't working.
Run the script to enable wind and change the waves:
```
cd <YOUR_VRX_WS>/src/vrx/vrx_gz/scripts
./update_sea_state_params.sh 1 5.0 "20000 0 0"
```
Verify the changes with:
```
git diff
```
Recompile:
```
cd <YOUR_VRX_WS>
GZ_VERSION=garden colcon build --merge-install
```
Run the simulation:
```
```
The WAM-V should slowly move (wind) and the waves should be bigger.
=> [Garden] Update environmental conditions

vrx_gz/worlds/gymkhana_task.sdf, vrx_gz/worlds/navigation_task.sdf, vrx_gz/worlds/perception_task.sdf, vrx_gz/worlds/scan_dock_deliver_task.sdf, vrx_gz/worlds/stationkeeping_task.sdf, vrx_gz/worlds/sydney_regatta.sdf, vrx_gz/worlds/wayfinding_task.sdf, vrx_gz/worlds/wildlife_task.sdf
A simple PR to remove the following comment from our sdfs:
```
```
Per discussion in #536 this comment does not seem to be true anymore.
Edit `sydney_regatta.sdf` to change the `pose` tag for the `sydney_regatta` model to alter the `z` value. Then rebuild and  run:
```
```
Observe that the pose of the heightmap has changed.
=> Remove obsolete comment about heightmap pose

vrx_urdf/wamv_gazebo/urdf/components/wamv_pinger.xacro, vrx_urdf/wamv_gazebo/urdf/wamv_gazebo.urdf.xacro
Fix issue #563.
The problem was in the `wamv_pinger.xacro`. We were creating a visual with an offset equals to the `position` of the pinger in world coordinates. This is wrong as the visual (if any) should represent the acoustic sensor and it should be inside the wam-v. 
I removed the visual and its collision as it's not very useful.
Bonus: I added some missing inertias, otherwise the default inertia values were incorrect. The inertias look good now:
* Recheck the instructions described in #531 to confirm that the pinger is still working correctly.
* Click on the WAM-V. Verify that the bounding box is now correct.
* Right click and select `View->Inertia` to confirm that the inertias are reasonable. **Note that the inertia visualization is very slow the first time that you request it. This …
=> [Garden] Fix issue #563 and inertias

vrx_gz/src/vrx_gz/bridges.py, vrx_gz/src/vrx_gz/model.py, vrx_gz/src/vrx_gz/payload_bridges.py, vrx_urdf/wamv_gazebo/urdf/thruster_layouts/wamv_gazebo_thruster_config.xacro
1. Follow the [customizing the WAM-V tutorial](https://github.com/osrf/vrx/wiki/2023-Customizing-the-WAM-V).
2. Edit the `example_thruster_config.yaml` and add a third thruster.
```
engine:
- prefix: "left"
position: "-2.373776 1.027135 0.318237"
orientation: "0.0 0.0 0.0"
- prefix: "right"
position: "-2.373776 -1.027135 0.318237"
orientation: "0.0 0.0 0.0"
- prefix: "middle"
position: "0 0 0.318237"
orientation: "0.0 0.0 0.0"
```
3. Follow the instructions and run the simulation with the custom thruster setup. Now, check that you have ros topics for the `middle` thruster.
```
ros2 topic list
```
You should see topics all these topic thrusters:
```
/wamv/thrusters/left/pos
/wamv/thrusters/left/thrust
/wamv/thrusters/middle/pos
/wamv/thrusters/middle/thrust
/wamv/thrusters/right/pos …
```
=> Enable the bridge for non-default thruster configurations

vrx_gz/CMakeLists.txt, vrx_gz/src/StationkeepingScoringPlugin.cc, vrx_gz/src/WayfindingScoringPlugin.cc, vrx_gz/src/WaypointMarkers.cc, vrx_gz/src/WaypointMarkers.hh, vrx_gz/worlds/2022_practice/practice_2022_stationkeeping0_task.sdf, vrx_gz/worlds/2022_practice/practice_2022_stationkeeping1_task.sdf, vrx_gz/worlds/2022_practice/practice_2022_stationkeeping2_task.sdf, vrx_gz/worlds/stationkeeping_task.sdf, vrx_gz/worlds/wayfinding_task.sdf
Fixes #596.
This PR restores the support to overlay a 3D marker on the scene. 
**Known limitations:** 
* Currently, it's not possible to render a `TEXT` marker. See [this open issue](https://github.com/gazebosim/gz-rendering/issues/487).
* It's not possible to pass a _text_ material like in Gazebo classic (`Gazebo/Red`). Instead, it's possible to set ambient and diffuse values. I decided not to expose it as it seems that we're always using the same color for the markers. Let me know otherwise and we could expose it.
Launch one of the stationkeeping/wayfinding world and check that a white marker shows up. Example:
```
ros2 launch vrx_gz competition.launch.py world:=practice_2022_stationkeeping2_task
```
=> Restore marker support

vrx_gz/worlds/nbpark.sdf
This pull request creates  a new world of the Nathan Benderson park. The [main model has been uploaded to Fuel](https://app.gazebosim.org/OpenRobotics/fuel/models/nathan_benderson_park).
Launch the simulation with the new world:
```
ros2 launch vrx_gz competition.launch.py world:=nbpark
```
Note: The WAM-V is spawned in the wrong place, we'll fix that in a separate pull request.
=> Adding Nathan Benderson Park world

vrx_gz/worlds/2022_practice/practice_2022_stationkeeping0_task.sdf, vrx_gz/worlds/2022_practice/practice_2022_stationkeeping1_task.sdf, vrx_gz/worlds/2022_practice/practice_2022_stationkeeping2_task.sdf, vrx_gz/worlds/stationkeeping_task.sdf
To review:
Inspect code to verify that `stationkeeping` is now spelled without an underscore everywhere.
Optionally, test the 4 stationkeeping_task worlds to make sure we aren't overlooking anything.
=> removing underscore from stationkeeping task name

vrx_gz/src/WildlifeScoringPlugin.cc, vrx_gz/src/WildlifeScoringPlugin.hh, vrx_gz/src/vrx_gz/bridges.py, vrx_gz/src/vrx_gz/launch.py, vrx_gz/worlds/2022_practice/practice_2022_wildlife0_task.sdf, vrx_gz/worlds/2022_practice/practice_2022_wildlife1_task.sdf, vrx_gz/worlds/2022_practice/practice_2022_wildlife2_task.sdf, vrx_gz/worlds/wildlife_task.sdf
This patch modifies the way we're publishing the animal poses in the wildlife task. Instead of publishing all the animals in a single topic but with a complicated message type, we now use multiple topics with a simple message type.
The new message type is `gz.msgs.Pose` in the Gazebo side and `geometry_msgs/msg/PoseStamped` in the ROS 2 side.
The new topics are:
```
/vrx/wildlife/animal0/pose
/vrx/wildlife/animal1/pose
/vrx/wildlife/animal2/pose
```
Launch any of the wildlife task worlds. E.g.:
```
ros2 launch vrx_gz competition.launch.py world:=practice_2022_wildlife0_task
```
In a separate terminal, run:
```
ros2 topic echo /vrx/wildlife/animal0/pose
```
You should get messages similar to:
```
---
header:
stamp:
sec: 30
nanosec: 840000000
frame_id: crocodile
pose:
position:
x: …
```
=> Use separate topics to publish animal poses

vrx_gz/config/wamv.yaml, vrx_gz/src/LightBuoyPlugin.hh, vrx_gz/src/NavigationScoringPlugin.cc, vrx_gz/src/NavigationScoringPlugin.hh, vrx_gz/worlds/2022_practice/practice_2022_follow_path0_task.sdf, vrx_gz/worlds/2022_practice/practice_2022_follow_path1_task.sdf, vrx_gz/worlds/2022_practice/practice_2022_follow_path2_task.sdf, vrx_gz/worlds/follow_path_task.sdf
Fixes #623 .
This patch updates the Follow-the-path task according to the discussion in issue #623 .
Launch the teleoperation node:
```
ros2 launch vrx_gz usv_joy_teleop.py
```
Launch a practice world. E.g.:
```
ros2 launch vrx_gz competition.launch.py world:=practice_2022_follow_path2_task
```
Verify the following things:
* Make sure that if you skip the first gate, nothing happens (no gates crossed or invalid reported on the console).
* Cross the starting gate (`+10` points).
* Make sure that if you cross another gate you get `10` points + a bonus. The bonus is declared as a parameter in the SDF.
* Make sure that if you skip a gate, you'll get 10 points for crossing the next gate and no bonus.
* Make sure that if you invalidate a gate (crossing it backwards), it no longer produces …
=> Update Follow-the-path scoring

.github/workflows/ci.yml, vrx_urdf/vrx_gazebo/src/vrx_gazebo/utils.py
This fixes issue #640
To test, follow this tutorial: https://github.com/osrf/vrx/wiki/empty_wamv_tutorial
Make sure there is no error message in the output; i.e. after running
```
ros2 launch vrx_gazebo generate_wamv.launch.py component_yaml:=`pwd`/empty_component_config.yaml thruster_yaml:=`pwd`/empty_thruster_config.yaml wamv_target:=`pwd`/wamv_target.urdf wamv_locked:=False
```
you should NOT see:
```
[generate_wamv.py-1] [ERROR] [1683911879.733853761] [configure_wamv]: 
[generate_wamv.py-1] This component/thruster configuration is NOT compliant with the (current) VRX constraints. A urdf file will be created, but please note that the above errors must be fixed for this to be a valid configuration for the VRX competition.
```
=> `generate_wamv.py` should not produce a compliance error on an empty WAMV

vrx_gz/hooks/resource_paths.dsv.in, vrx_gz/hooks/resource_paths.sh, vrx_gz/src/vrx_gz/launch.py, vrx_gz/worlds/2023_practice/practice_2023_acoustic_perception0_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_acoustic_perception1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_acoustic_perception2_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_acoustic_tracking0_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_acoustic_tracking1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_acoustic_tracking2_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_follow_path0_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_follow_path1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_follow_path2_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_perception0_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_perception1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_perception2_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_scan_dock_deliver0_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_scan_dock_deliver1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_scan_dock_deliver2_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_stationkeeping0_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_stationkeeping1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_stationkeeping2_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_wayfinding0_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_wayfinding1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_wayfinding2_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_wildlife0_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_wildlife1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_wildlife2_task.sdf
See #647.
After recompiling you should be able to launch the worlds with:
```
ros2 launch vrx_gz competition.launch.py world:=practice_2023_follow_path1_task
```
Verify a few worlds to make sure that they load correctly.
=> Rename 2022_practice worlds to 2023_practice

vrx_gz/CMakeLists.txt
This addresses issue #670 and produces a nice clean build with no errors or warnings.
To test, use our new and improved [installation tutorial](https://github.com/osrf/vrx/wiki/installation_tutorial). It is not necessary to have a completely fresh system, but you will need to install the Gazebo prelease repo and the binary for `ros_gz`. Then make a new workspace and build VRX. It should build pretty quickly and with no errors.
=> add .cc to WaypointMarkers in CMakeLists.txt

vrx_gz/src/USVWind.cc
Test: run VRX normally.  Echo one of the wind topics, eg:
```
gz topic --echo --topic /vrx/debug/wind/speed
```
Pause the simulation.  You should see the topic stop publishing.  Unpause, watch the messages scroll.
=> fix wind plugin pause

vrx_gz/src/vrx_gz/bridges.py, vrx_gz/src/vrx_gz/model.py, vrx_gz/src/vrx_gz/payload_bridges.py, vrx_urdf/wamv_gazebo/urdf/components/wamv_pinger.xacro
See issue #641.
The problem was our well known Gazebo "feature" that eliminates fixed joints when converting from `URDF` to `SDF`. Then, the pinger link disappeared. I converted the fixed joint into a revolute joint with no movement to bypass the problem.
* Launch the simulation as usual:
```
```
* Look at the WAMV in the entity tree and verify that there is a "pinger" listed. If you select the pinger link, you should observe a tiny sphere between the two pontoons as I enabled a small visual for reference.
* Additionally, if you comment out the line `221` in `wamv_gazebo.urdf.xacro`:
```
<xacro:wamv_pinger name="pinger" position="-528 191 -2.0" />
```
You shouldn't see the pinger link in the WAMV entity tree and the …
=> Fix issue #641

vrx_gz/launch/competition.launch.py, vrx_gz/src/vrx_gz/launch.py
This provides the quickest fix to issue #680 by extracting a normalized world name from any incoming path, and adding a few likely names to our list of worlds that we recognize and create bridges for. It doesn't fix the deeper conceptual problems described in #680.
Run a task using an absolute path:
```
ros2 launch vrx_gz competition.launch.py world:=`pwd`/src/vrx/vrx_gz/worlds/stationkeeping_task.sdf
```
in another terminal run
```
ros2 topic list
```
and verify that you see the correct list of topics. Next, rename one of our task worlds to one of the generic names we use in our testing, and check the topics again to verify that it still works:
```
cp `pwd`/src/vrx/vrx_gz/worlds/stationkeeping_task.sdf stationkeeping0.sdf
ros2 launch vrx_gz competition.launch.py …
```
=> support full paths to world files

vrx_gz/worlds/2023_practice/practice_2023_acoustic_perception0_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_acoustic_perception1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_acoustic_perception2_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_acoustic_tracking0_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_acoustic_tracking1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_acoustic_tracking2_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_follow_path0_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_follow_path1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_perception0_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_perception1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_scan_dock_deliver0_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_scan_dock_deliver1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_stationkeeping0_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_stationkeeping1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_stationkeeping2_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_wayfinding0_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_wayfinding1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_wayfinding2_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_wildlife0_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_wildlife1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_wildlife2_task.sdf
This PR adjusts the wavefield parameters for the practice worlds to cover a broader spectrum of possibilities using our recently updated wavefield envelope (see #684). The changes introduced to the worlds are as follows:
* I updated all easy (0) worlds so they have no waves at all.
* I changed all intermediate (1) worlds to use period 6, gain 0.6, which produces mild swells. I also varied the direction of the wavefield so teams will not expect it to always stay the same.
* I changed the wavefield of some of the hard (2) worlds so they are not all the same. Specifically, I left the period of 2 and gain of 2.0 for tasks that rely on perception. For other tasks, such as stationkeeping and wayfinding I used period 6, gain 0.8 to produce medium swells. I also introduced some simple variations …
=> Adjust practice worlds to make use of new wavefield model envelope

vrx_gz/launch/competition.launch.py
A simple fix to address problems with task-specific bridges failing, described in #680 and https://github.com/osrf/vrx-docker/pull/60
First observe that task specific bridges are currently failing if the competition world is specified using an absolute path:
```
cd vrx_ws
cp src/vrx/vrx_gz/worlds/2023_practice/practice_2023_stationkeeping0_task.sdf stationkeeping0.sdf
ros2 launch vrx_gz competition.launch.py world:=`pwd`/stationkeeping0
```
Note that `gz topic -l` shows
```
/vrx/stationkeeping/goal
/vrx/stationkeeping/mean_pose_error
/vrx/stationkeeping/pose_error
```
but `ros2 topic list` does not.
Now checkout this branch, build again, and re-run the launch command above. Verify that the competition topics now show up.
=> enable competition bridges when world uses absolute paths

vrx_gz/launch/competition.launch.py, vrx_gz/src/vrx_gz/launch.py
This PR adds the `extra_gz_args` option to `competition.launch.py` and passes it through to `gz sim`. We had something similar in VRX classic so we could use gazebo options without having to implement command line arguments for all of them. (There might be a cleaner way to do this; if so please advise.)
The immediate reason for doing this is so we can use gz sim's recording functionality, which we need to get playback working.
Try passing some arguments through to gz sim:
```
ros2 launch vrx_gz competition.launch.py headless:=false world:=stationkeeping_task extra_gz_args:="--record_period 0.01 --record_path $HOME/.gz_sim_arg_test --log_overwrite"
```
Check that logs are written to `$HOME/.gz_sim_arg_test`.
Bonus: adding support for "paused" argument. To test:
```
ros2 launch vrx_gz …
```
=> add command line argument for passing extra args to gz sim

vrx_gz/src/AcousticTrackingScoringPlugin.cc, vrx_gz/src/vrx_gz/payload_bridges.py, vrx_gz/worlds/2023_practice/practice_2023_acoustic_perception0_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_acoustic_perception1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_acoustic_perception2_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_acoustic_tracking0_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_acoustic_tracking1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_acoustic_tracking2_task.sdf, vrx_gz/worlds/acoustic_perception_task.sdf, vrx_gz/worlds/acoustic_tracking_task.sdf, vrx_gz/worlds/gymkhana_task.sdf, vrx_urdf/vrx_gazebo/config/wamv_config/component_compliance/numeric.yaml, vrx_urdf/vrx_gazebo/config/wamv_config/example_component_config.yaml, vrx_urdf/wamv_gazebo/urdf/components/wamv_pinger.xacro, vrx_urdf/wamv_gazebo/urdf/wamv_gazebo.urdf.xacro
Fixes #691 
This pull request updates the topics associated with the pinger functionality.
The beacon located in the water uses a topic to set its position. The default topic is now `/pinger/set_pinger_position`.
The acoustic sensor mounted on the WAM-V uses a topic to access the sensor data, that estimates distance to the pinger. The default topic is now `/wamv/sensors/acoustics/receiver/range_bearing`.
This PR has a implications in a few places: acoustic_perception task, acoustic_tracking task and also wamv_generation.
Follow the instructions from https://github.com/osrf/vrx/pull/609
**Important**: In step (3), echo the topic `/wamv/sensors/acoustics/receiver/range_bearing` instead.
Follow the instructions from https://github.com/osrf/vrx/pull/614
**Important**: Uncomment the block …
=> Fix issue #691

vrx_gz/worlds/2023_practice/practice_2023_perception1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_perception2_task.sdf
aims to close #689 
Summary:
A detailed analysis of the various parameters can be found in the discussion of the associated issue.
The following updates have been done:
1. Round Buoys:
geometry radius updated to 0.21(for both *perception_task1* and *perception_task2*)
updated drag coefficient to 75(for both *perception_task1* and *perception_task2*)
updated spawning z=0.7 in *perception_task1* 
2. Marker Buoys
Updated spawning z=0.7 for both (*perception_task1* and *perception_task2*)
Updated linear drag coefficient to 50 in *perception_task2* to reduce the magnitude of oscillations a little.
Test:
Run `2023_practice/practice_2023_perception1_task` and `2023_practice/practice_2023_perception2_task` worlds
Results:
https://github.com/osrf/vrx/assets/64950661/d2787769-611b-406a-bdbf-f6d7c276 …
=> Reduce oscillations of buoys in perception task

vrx_urdf/wamv_gazebo/urdf/components/wamv_imu.xacro
In reference to Issue #675 
IMU initializes to local reference frame on WAM-V spawn.
This can be checked by echoing IMU sensor data on spawn.
Add the following to `wamv_imu.xacro` to link IMU to parent reference frame:
```
<orientation_reference_frame>
<localization>ENU</localization>
</orientation_reference_frame>
```
Launch with 
```
```
Confirm orientation values with 
```
ros2 topic echo /wamv/sensors/imu/imu/data
```
Change orientation values in `competition.launch.py` and re-launch. Changing spawn orientation to align with world axes shows IMU reflects orientation in global frame.
=> Set IMU to reflect sensor position in global coordinates

vrx_gz/launch/competition.launch.py, vrx_gz/src/vrx_gz/launch.py
Fix issue #693.
This patch allows us to pass an extra `competition_mode` command line argument to enable/disable certain ROS 2 topics. As an example, I disabled the wind debug topics when `competition_mode` is enabled.
Run the simulation as usual:
```
ros2 launch vrx_gz competition.launch.py world:=practice_2023_stationkeeping2_task
```
Verify that the ROS 2 wind debug topics are available:
```
ros2 topic list
...
/vrx/debug/wind/direction
/vrx/debug/wind/speed
...
```
Now, stop the simulation and run it again in competition mode:
```
ros2 launch vrx_gz competition.launch.py world:=practice_2023_stationkeeping2_task competition_mode:=true
```
And verify again the ROS 2 debug wind topics:
```
ros2 topic list
```
You shouldn't see them now.
=> Create competition_mode argument

LICENSE, vrx_gz/worlds/2023_practice/practice_2023_stationkeeping1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_wayfinding1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_wayfinding2_task.sdf
Fixes #707.
It should also be autodetected by GitHub now (in the `About` right panel of the landing page).
Bonus: Minor fixes of world name typos.
=> Add license

vrx_urdf/wamv_gazebo/urdf/components/wamv_camera.xacro
As @M1chaelM reported, the treeline might look inconsistent from the cameras.
Increasing the clipping fixes this issue:
https://private-user-images.githubusercontent.com/1440739/262057592-e62bbc8e-3015-42c0-941d-112784203f1b.webm?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE2OTI3NDIxNjYsIm5iZiI6MTY5Mjc0MTg2NiwicGF0aCI6Ii8xNDQwNzM5LzI2MjA1NzU5Mi1lNjJiYmM4ZS0zMDE1LTQyYzAtOTQxZC0xMTI3ODQyMDNmMWIud2VibT9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMwODIyVDIyMDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzYTE2NjkxMjc4YTgzOTM3YWFkNzA3NjJiNDc2NmUzYTViNzdiYjUyZjMwY2FmMTFiM …
=> Update camera clip

vrx_gz/models/obstacle_course/model.sdf, vrx_gz/models/short_navigation_course_0/model.sdf, vrx_gz/models/short_navigation_course_1/model.sdf, vrx_gz/models/short_navigation_course_2/model.sdf, vrx_gz/worlds/2023_practice/practice_2023_acoustic_tracking0_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_acoustic_tracking1_task.sdf, vrx_gz/worlds/2023_practice/practice_2023_acoustic_tracking2_task.sdf, vrx_gz/worlds/acoustic_tracking_task.sdf, vrx_gz/worlds/stationkeeping_task.sdf, vrx_gz/worlds/sydney_regatta.sdf, vrx_gz/worlds/wayfinding_task.sdf
This PR continues the work done in #699 with the rest of the round buoys. It also fixes the orientation of the Sydney Regatta buoys.
Launch any of the worlds and verify that the buoys are still OK. E.g.:
```
```
=> Buoy update

vrx_gz/src/AcousticPerceptionScoringPlugin.cc
This is a bug fix for the acoustic perception task. While running phase 2, I noticed an issue with the scoring. The score should be equal to the elapsed time needed to reach the pinger. However, if the team doesn't reach the pinger, the plugin was reporting a score of `0`. Keep in mind that the lower the score the better. Instead, in that case the score should equal to the total running time (e.g. `300`).
How to test it?
Run this task and let it timeout while watching the score.
```
ros2 launch vrx_gz competition.launch.py world:=practice_2023_acoustic_perception0_task
```
And then:
```
ros2 topic echo /vrx/task/info
```
=> Initialize acoustic perception score

vrx_gz/launch/vrx_environment.launch.py
Reverts competition.launch.py to main branch and creates a new launch file, vrx_environment.launch.py, to launch the world and wamv or other vehicle separately.
To test:
* Confirm competition script opens and runs normally, with working WAMV:
`ros2 launch vrx_gz competition.launch.py world:=sydney_regatta`
* Launch environment and vehicle separately:
`ros2 launch vrx_gz vrx_environment.launch.py world:=sydney_regatta`
`ros2 launch vrx_gz spawn.launch.py name:=wamv world:=sydney_regatta model:=wam-v x:=-535 y:=162 z:=0 R:=0 P:=0 Y:=1`
=> Launch VRX with or without the WAMV

vrx_gz/config/roboboat.yaml
Maps joysticks on gamepad to each thruster on roboboat resulting in a differential drive system. Scaling is decreased in comparison to WAM-V config.
See the [tutorial](https://github.com/osrf/vrx/wiki/teleop_roboboat_tutorial) for how it is used and testing. 
I've had past issues with my gamepad axes not matching intended command direction. This config matches the WAM-V config for direction/axis, so should be fine, but verification is appreciated.
=> Add Configuration File Roboboat Teleop

.github/workflows/ci.yml
This is a full rewrite of the CI system mostly to use common artifacts in the ROS Community, summary of the changes:
* Do not use a base image from npslearninglab anymore. Instead of use one of the OCI images created in https://github.com/sloretz/ros_oci_images that are updated more often than the official dockerhub, see https://discourse.ros.org/t/docker-images-for-ros-updated-more-frequently/36931
* The CI now runs daily to check for new Jazzy packages added to the repository in the case that we could find regressions in updates.
* It runs on every push to the repository
* Use ros-tooling/setup-ros-ci github action to configure a ros environment and install some build tools not in the docker image
* Use ros-tooling/action-ros-ci to handle the compilation and testing by providing a …
=> Migrate CI to use Jazzy + Harmonic: use ros-tooling actions

dev/Dockerfile
Since the development Dockerfile used for the repository was referred to be the one in https://github.com/HonuRobotics/dockwater/tree/main/jazz the PR import it here to be close to the code and easy to find by the users.
The first commit imported the file as-it is in the dockwater repository and the second 05a270448181a5667da13039898630dfb5c83f70 does a full clean-up including:
* Remove all sudo references
* Re-order steps 
* From the list of development packages, remove those already installed by gz-harmonic, ROS 2 Jazzy and the Ubuntu base image.
From here we can think on creating different docker images to be use in CI, dev and releasing based on the same Dockerfile structure.
=> Import the dockwater/jazzy Dockerfile and cleanup

README.md
Update README to reflect the changes done in #794 and give credit to Honu/RoboNation for doing the latest development in this area.
:warning: before merging, we will need to deploy the branching model based on ROS 2 release names and create the `humble` branch from the `garden` branch and branch out `main` to be named `jazzy`.
=> Update README: new Gazebo and ROS versions supported
